@extends('accounting::components.layouts.master')

@section('title', 'Customer Ledger')

@section('content')
    <div class="card">
        <div class="card-header border-bottom">
            <h5 class="card-title mb-0">Customer Ledger</h5>
        </div>
        <div class="card-datatable">
            <table class="datatables-users table border-top">
                <thead>
                    <tr></tr> <!-- Will be dynamically generated by JS -->
                </thead>
            </table>
        </div>
    </div>
@endsection

@section('page-script')
    @vite(['resources/js/HS/data-table.js']) <!-- This is your JS file -->

    <script>
        window.dataTableConfig = {
            ajaxUrl: "{{ route('accounting.customer-ledger.entriesList') }}",
            actionsRoutePrefix: '/accounting/customer-ledger',
            hideAddButton: true, // This will hide the Add Customer button
            columns: {
                id: {
                    type: 'text',
                    title: 'ID'
                },
                name: {
                    type: 'link',
                    linkTo: '/accounting/customer-ledger', // This is base URL
                    linkSuffix: '/view', // Suffix to append after ID
                    title: 'Name'
                },
                email: {
                    type: 'text',
                    title: 'Email'
                },
                phone: {
                    type: 'text',
                    title: 'Phone'
                },
                address: {
                    type: 'text',
                    title: 'Address'
                },
                balance: {
                    type: 'text',
                    title: 'Balance'
                },
                created_at: {
                    type: 'text',
                    title: 'Created Date'
                }
            },
            permissions: {
                canView: true,
                canAdd: true
            }
        };
    </script>
@endsection