@extends('layouts.layoutMaster')

@section('title', 'Trial Balance Report')

{{-- Vendor Styles --}}
@section('vendor-style')
@vite([
    'resources/assets/vendor/libs/datatables-bs5/datatables.bootstrap5.scss',
    'resources/assets/vendor/libs/select2/select2.scss',
    'resources/assets/vendor/libs/flatpickr/flatpickr.scss'
])
@endsection

{{-- Vendor Scripts --}}
@section('vendor-script')
@vite([
    'resources/assets/vendor/libs/datatables-bs5/datatables-bootstrap5.js',
    'resources/assets/vendor/libs/select2/select2.js',
    'resources/assets/vendor/libs/flatpickr/flatpickr.js'
])
@endsection

@section('page-style')
<style>
    /* Header and footer text to white */
    .table thead th,
    .table tfoot td {
        color: #ffffff !important;
        background-color: #002F6C !important;
        border: 1px solid #000 !important;
    }

    .table tbody td {
        border: 1px solid #000 !important;
    }

    .table tfoot td {
        font-weight: bold;
    }

    .table th,
    .table td {
        vertical-align: middle !important;
        text-align: center;
    }
</style>
@endsection


@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <!-- Date Picker and Export Button -->
    <form method="GET" action="{{ route('accounting.trial-balance.index') }}">
        <div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2">
            <div class="input-group w-auto">
                <span class="input-group-text">Duration</span>
                <input type="text" name="date_range" class="form-control flatpickr-range" value="{{ request('date_range') }}" placeholder="Start Date to End Date" />
                <button type="submit" class="btn btn-success">OK</button>
                <a href="{{ route('accounting.trial-balance.index') }}" class="btn btn-outline-secondary">Clear</a>
            </div>
            <div>
                <button type="submit" formaction="{{ route('accounting.trial-balance.export-pdf') }}" class="btn btn-primary">
    Export as PDF
</button>

            </div>
        </div>
    </form>

    <!-- Report Header Section -->
    <div class="bg-light p-3 rounded mb-4">
        <h4 class="fw-bold mb-3">TRIAL BALANCE</h4>
        <div class="row g-3">
            <div class="col-md-4">
                <div><strong>Data Period:</strong> {{ request('date_range') ?? 'All Time' }}</div>
            </div>
            <div class="col-md-4">
                <div><strong>Generated By:</strong> Admin</div>
            </div>
            <div class="col-md-4">
                <div><strong>Generated On:</strong> {{ now()->format('D d, Y') }}</div>
            </div>
        </div>
    </div>

    <!-- Trial Balance Table -->
    <div class="card">
        <div class="table-responsive">
            <table class="table mb-0 table-bordered">
                <thead style="background-color: #002F6C; color: #ffffff;">
                    <tr>
                        <th rowspan="2">Account</th>
                        <th colspan="2">Opening</th>
                        <th colspan="2">Transaction</th>
                        <th colspan="2">Closing</th>
                    </tr>
                    <tr>
                        <th>Debit (SAR)</th>
                        <th>Credit (SAR)</th>
                        <th>Debit (SAR)</th>
                        <th>Credit (SAR)</th>
                        <th>Debit (SAR)</th>
                        <th>Credit (SAR)</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $totalOpeningDebit = $totalOpeningCredit = 0;
                        $totalTransactionDebit = $totalTransactionCredit = 0;
                        $totalClosingDebit = $totalClosingCredit = 0;
                    @endphp

                    @foreach($trialBalanceData as $row)
                        <tr>
                            <td>
                                <a href="{{ route('accounting.ledger.view', ['id' => $row['account_id']]) }}{{ request('date_range') ? '?date_range=' . urlencode(request('date_range')) : '' }}" 
                                   target="_blank" 
                                   style="text-decoration: underline; color: #002F6C;">
                                    {{ $row['account_name'] }}
                                </a>
                            </td>
                            <td>{{ number_format($row['opening_debit'], 2) }}</td>
                            <td>{{ number_format($row['opening_credit'], 2) }}</td>
                            <td>{{ number_format($row['transaction_debit'], 2) }}</td>
                            <td>{{ number_format($row['transaction_credit'], 2) }}</td>
                            <td>{{ number_format($row['closing_debit'], 2) }}</td>
                            <td>{{ number_format($row['closing_credit'], 2) }}</td>
                        </tr>
                        @php
                            $totalOpeningDebit += $row['opening_debit'];
                            $totalOpeningCredit += $row['opening_credit'];
                            $totalTransactionDebit += $row['transaction_debit'];
                            $totalTransactionCredit += $row['transaction_credit'];
                            $totalClosingDebit += $row['closing_debit'];
                            $totalClosingCredit += $row['closing_credit'];
                        @endphp
                    @endforeach
                </tbody>
                <tfoot style="background-color: #002F6C; color: #ffffff; font-weight: bold;">
                    <tr>
                        <td>Total</td>
                        <td>{{ number_format($totalOpeningDebit, 2) }}</td>
                        <td>{{ number_format($totalOpeningCredit, 2) }}</td>
                        <td>{{ number_format($totalTransactionDebit, 2) }}</td>
                        <td>{{ number_format($totalTransactionCredit, 2) }}</td>
                        <td>{{ number_format($totalClosingDebit, 2) }}</td>
                        <td>{{ number_format($totalClosingCredit, 2) }}</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection

@section('page-script')
<script>
    document.addEventListener('DOMContentLoaded', function () {
        flatpickr(".flatpickr-range", {
            mode: "range",
            dateFormat: "Y-m-d",
            locale: {
                rangeSeparator: " to "
            },
            onReady: function (selectedDates, dateStr, instance) {
                const buttonWrapper = document.createElement('div');
                buttonWrapper.classList.add('d-flex', 'justify-content-end', 'mt-2');

                const okButton = document.createElement('button');
                okButton.type = 'button';
                okButton.className = 'btn btn-sm btn-primary me-1';
                okButton.textContent = 'OK';
                okButton.addEventListener('click', () => instance.close());

                const clearButton = document.createElement('button');
                clearButton.type = 'button';
                clearButton.className = 'btn btn-sm btn-secondary';
                clearButton.textContent = 'Clear';
                clearButton.addEventListener('click', () => {
                    instance.clear();
                    instance.close();
                });

                buttonWrapper.appendChild(okButton);
                buttonWrapper.appendChild(clearButton);
                instance.calendarContainer.appendChild(buttonWrapper);
            }
        });
    });
</script>
@endsection
