@extends('accounting::components.layouts.master')

@section('title', 'Ledger Details')

@section('page-style')
    <style>
        /* Print-specific styles */
        @media print {
            body {
                -webkit-print-color-adjust: exact !important;
                print-color-adjust: exact !important;
                background: white !important;
            }

            /* Hide elements you don't want in print */
            .no-print,
            .layout-navbar,
            .layout-menu,
            .footer,
            nav,
            .pagination {
                display: none !important;
            }

            body * {
                visibility: hidden !important;
            }

            .printable-section,
            .printable-section * {
                visibility: visible !important;
            }

            .printable-section {
                position: absolute;
                left: 0;
                top: 0;
                width: 100%;
                background: white !important;
            }
        }

        .date-info-box {
            border: 1px solid #dee2e6;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 4px;
            background-color: #f8f9fa;
            width: 300px;
        }

        .date-info-box p {
            margin-bottom: 5px;
        }
    </style>
@endsection

@section('content')
    <div class="container py-4">

        {{-- Print Button (not printed) --}}
        <div class="no-print mb-3">
            <button class="btn btn-primary" onclick="window.print()">Print Ledger</button>
        </div>

        {{-- Printable Ledger --}}
        <div class="card p-4 printable-section">
            <div class="d-flex justify-content-between">
                <div>
                    <h3 class="mb-2">LEDGER</h3>
                    <p class="mb-0">Demo - Company امتحان</p>
                    <p class="mb-0">company@email.com</p>
                    <p class="mb-0">1234567891</p>

                    {{-- Date Info Box --}}
                    <div class="date-info-box mt-3">
                        @php
                            // Get the earliest and latest dates from the data
                            $dates = $paginatedData->pluck('created_at')->filter()->sort();
                            $firstDate = $dates->first();
                            $lastDate = $dates->last();
                        @endphp

                        <p><strong>Data From:</strong>
                            {{ $firstDate ? \Carbon\Carbon::parse($firstDate)->format('d-m-Y') : 'N/A' }}</p>
                        <p><strong>Data To:</strong>
                            {{ $lastDate ? \Carbon\Carbon::parse($lastDate)->format('d-m-Y') : 'N/A' }}</p>
                        <p><strong>Generated On:</strong> {{ now()->format('d-m-Y') }}</p>
                    </div>
                </div>

                <div class="bg-light p-3" style="min-width: 250px;">
                    <p><strong>Generated By</strong><br>
                        {{ $paginatedData->firstWhere('type', 'entry')->created_by ?? '-' }}
                    </p>
                    <p><strong>Account Name</strong><br>{{ $accountChart->account_name }}</p>
                    <p><strong>Account Category</strong><br>{{ $accountChart->mainCategory->name ?? '-' }}</p>
                    <p><strong>Account SubCategory</strong><br>{{ $accountChart->subcategory->name ?? '-' }}</p>
                </div>
            </div>

            <div class="table-responsive mt-3">
                <table class="table table-bordered text-center">
                    <thead class="bg-dark">
                        <tr>
                            <th style="color: #ffffff;">SL NO</th>
                            <th style="width: 145px; color: #ffffff;">ENTRY DATE</th>
                            <th style="width: 145px; color: #ffffff;">DUE DATE</th>
                            <th style="color: #ffffff;">DESCRIPTION</th>
                            <th style="color: #ffffff;">CLIENT</th>
                            <th style="color: #ffffff;">CREDIT AMOUNT</th>
                            <th style="color: #ffffff;">DEBIT AMOUNT</th>
                            <th style="color: #ffffff;">TOTAL CREDIT</th>
                            <th style="color: #ffffff;">TOTAL DEBIT</th>
                            <th style="color: #ffffff;">BALANCE</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($paginatedData as $index => $data)
                            <tr @if ($data->type === 'chart') style="background-color: #f3f6f9;" @endif>
                                <td>{{ $paginatedData->firstItem() + $index }}</td>
                                <td>
                                    {{ $data->entry_date ? \Carbon\Carbon::parse($data->entry_date)->format('d-m-Y') : '-' }}
                                </td>
                                <td>
                                    {{ $data->due_date ? \Carbon\Carbon::parse($data->due_date)->format('d-m-Y') : '-' }}
                                </td>
                                <td>{{ $data->description }}</td>
                                <td>{{ $data->client_name ?? '-' }}</td>
                                <td>{{ number_format($data->credit, 2) }}</td>
                                <td>{{ number_format($data->debit, 2) }}</td>
                                <td>{{ number_format($data->cumulative_credit, 2) }}</td>
                                <td>{{ number_format($data->cumulative_debit, 2) }}</td>
                                <td>{{ number_format($data->balance, 2) }}</td>
                            </tr>
                        @endforeach

                        <tr style="font-weight: bold; background-color: #d1ecf1;">
                            <td colspan="5" class="text-end">Total (Upto current Page):</td>
                            <td>{{ number_format($totals['total_credit'], 2) }}</td>
                            <td>{{ number_format($totals['total_debit'], 2) }}</td>
                            <td>{{ number_format($cumulativeCredit ?? $totals['total_credit'], 2) }}</td>
                            <td>{{ number_format($cumulativeDebit ?? $totals['total_debit'], 2) }}</td>
                            <td>{{ number_format($totals['total_balance'], 2) }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            {{-- Pagination Links (hidden in print) --}}
            <div class="d-flex justify-content-center mt-3 no-print">
                {{ $paginatedData->links('pagination::bootstrap-4') }}
            </div>
        </div>
    </div>
@endsection
