@extends('layouts.layoutMaster')

@section('title', 'Ledger Details')

@section('content')
    <div class="container py-4">
        <button class="btn btn-primary mb-3" onclick="window.print()">Print Ledger</button>

        <div class="card p-4">
            <div class="d-flex justify-content-between">
                <div>
                    <h3 class="mb-2">LEDGER</h3>
                    <p class="mb-0">Demo - Company امتحان</p>
                    <p class="mb-0">company@email.com</p>
                    <p class="mb-0">1234567891</p>
                </div>
                <div class="bg-light p-3" style="min-width: 250px;">
                    <p><strong>Generated By</strong><br>
                        {{ $paginatedData->firstWhere('type', 'entry')->created_by ?? '-' }}
                    </p>
                    <p><strong>Account Name</strong><br>{{ $accountChart->account_name }}</p>
                    <p><strong>Account Category</strong><br>{{ $accountChart->mainCategory->name ?? '-' }}</p>
                    <p><strong>Account SubCategory</strong><br>{{ $accountChart->subcategory->name ?? '-' }}</p>
                    <p><strong>Generated Date</strong><br>{{ now()->format('d-m-Y') }}</p>
                </div>
            </div>

            <div class="table-responsive mt-4">
                <table class="table table-bordered text-center">
                    <thead class="bg-dark">
                        <tr>
                            <th style="color: #ffffff;">SL NO</th>
                            <th style="width: 145px; color: #ffffff;">ENTRY DATE</th>
                            <th style="width: 145px; color: #ffffff;">DUE DATE</th>
                            <th style="color: #ffffff;">DESCRIPTION</th>
                            <th style="color: #ffffff;">CLIENT</th>
                            <th style="color: #ffffff;">CREDIT AMOUNT</th>
                            <th style="color: #ffffff;">DEBIT AMOUNT</th>
                            <th style="color: #ffffff;">TOTAL CREDIT</th>
                            <th style="color: #ffffff;">TOTAL DEBIT</th>
                            <th style="color: #ffffff;">BALANCE</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($paginatedData as $index => $data)
                            <tr @if ($data->type === 'chart') style="background-color: #f3f6f9;" @endif>
                                <td>{{ $paginatedData->firstItem() + $index }}</td>
                                <td style="width: 120px;">
                                    {{ $data->entry_date ? \Carbon\Carbon::parse($data->entry_date)->format('d-m-Y') : '-' }}
                                </td>
                                <td style="width: 120px;">
                                    {{ $data->due_date ? \Carbon\Carbon::parse($data->due_date)->format('d-m-Y') : '-' }}
                                </td>
                                <td>{{ $data->description }}</td>
                                <td>{{ $data->client_name ?? '-' }}</td>
                                <td>{{ number_format($data->credit, 2) }}</td>
                                <td>{{ number_format($data->debit, 2) }}</td>
                                <td>{{ number_format($data->cumulative_credit, 2) }}</td>
                                <td>{{ number_format($data->cumulative_debit, 2) }}</td>
                                <td>{{ number_format($data->balance, 2) }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            {{-- Pagination Links --}}
            <div class="d-flex justify-content-center mt-3">
                {{ $paginatedData->links('pagination::bootstrap-4') }}
            </div>
        </div>
    </div>
@endsection
