@extends('layouts.layoutMaster')

@section('title', 'Ledger Entries')

<!-- Vendor Styles -->
@section('vendor-style')
@vite([
    'resources/assets/vendor/libs/datatables-bs5/datatables.bootstrap5.scss',
    'resources/assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.scss',
    'resources/assets/vendor/libs/datatables-buttons-bs5/buttons.bootstrap5.scss',
    'resources/assets/vendor/libs/select2/select2.scss',
    'resources/assets/vendor/libs/@form-validation/form-validation.scss',
    'resources/assets/vendor/libs/animate-css/animate.scss',
    'resources/assets/vendor/libs/sweetalert2/sweetalert2.scss'
])
@endsection

<!-- Vendor Scripts -->
@section('vendor-script')
@vite([
    'resources/assets/vendor/libs/moment/moment.js',
    'resources/assets/vendor/libs/datatables-bs5/datatables-bootstrap5.js',
    'resources/assets/vendor/libs/select2/select2.js',
    'resources/assets/vendor/libs/@form-validation/popular.js',
    'resources/assets/vendor/libs/@form-validation/bootstrap5.js',
    'resources/assets/vendor/libs/@form-validation/auto-focus.js',
    'resources/assets/vendor/libs/cleave-zen/cleave-zen.js',
    'resources/assets/vendor/libs/sweetalert2/sweetalert2.js'
])
@endsection

@section('content')
<div class="card">
    <div class="card-header border-bottom">
        <h5 class="card-title mb-0">Ledger Entries</h5>
    </div>
    <div class="card-datatable">
        <table class="datatables-users table border-top">
            <thead>
                <tr></tr> <!-- Will be dynamically generated by JS -->
            </thead>
        </table>
    </div>
</div>
@endsection

@section('page-script')
@vite(['resources/js/HS/data-table.js']) <!-- This is your JS file -->

<script>
    window.dataTableConfig = {
        ajaxUrl: "{{ route('accounting.ledger.entriesList') }}",
        actionsRoutePrefix: '/accounting/ledger',
        addButton: {
            label: 'Add Ledger',
            url: "{{ route('accounting.ledger.create') }}"
        },
        columns: {
            id: { type: 'text' },
            account_name: { 
                type: 'link', 
                linkTo: '/accounting/ledger',  // This is base URL
                linkSuffix: '/view'         // Suffix to append after ID
            },
            sub_category: { type: 'text' },
            main_category: { type: 'text' }
        },
        permissions: {
            canView: true,
            canAdd: true
        }
    };
</script>

@endsection
