@extends('accounting::components.layouts.master')

@section('title', 'Ledger Entries')

@section('content')
    <div class="card">
        <div class="card-header border-bottom">
            <h5 class="card-title mb-0">Ledger Entries</h5>
        </div>
        <div class="card-datatable">
            <table class="datatables-users table border-top">
                <thead>
                    <tr></tr> <!-- Will be dynamically generated by JS -->
                </thead>
            </table>
        </div>
    </div>
@endsection

@section('page-script')
    @vite(['resources/js/HS/data-table.js'])

    <script>
        window.dataTableConfig = {
            ajaxUrl: "{{ route('accounting.ledger.entriesList') }}",
            actionsRoutePrefix: '/accounting/ledger',

            // 👇 Set this to true to completely hide the "Add" button
            hideAddButton: true,

            addButton: {
                label: 'Add Ledger',
                url: "{{ route('accounting.ledger.create') }}"
            },

            columns: {
                id: { type: 'text' },
                account_name: { type: 'link', linkTo: '/accounting/ledger', linkSuffix: '/view' },
                sub_category: { type: 'text' },
                main_category: { type: 'text' }
            },

            permissions: {
                canView: true,
                canAdd: true
            }
        };
    </script>
@endsection
